minimum_pre_commit_version: 4.0.1
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.7.4
    hooks:
      # Run the linter
      - id: ruff
        name: ruff linter
        alias: lint
      # Run the formatter
      - id: ruff-format
        name: ruff formatter
        alias: format